#!/usr/bin/env sh
# Wrapper for llama-server that adds -m "${MODEL}" if MODEL is set.
# Similar for `$PORT` --> `--port $PORT`

if [ -n "${MODEL}" ]; then
  set -- -m "${MODEL}" "$@"
fi

if [ -n "${PORT}" ]; then
  set -- --port "${PORT}" "$@"
fi

exec llama-server "$@"
