# extensions
# https://docs.docker.com/reference/compose-file/extension/
# Prefixed these with `x-`

# Inference Engines (Runtimes)
x-engine: &x-engine
  devices:
    # Direct Rendering Infrastructure (dri) - exposes renderer nodes (renderD128) and compute shaders, used by Vulkan/Mesa
    - /dev/dri:/dev/dri
    # Kernel Fusion Driver (kfd) - primary compute interface - essential for HIP/ROCm
    - /dev/kfd:/dev/kfd
  group_add:
    - render
    - video
  security_opt:
    - seccomp:unconfined
    - apparmor:unconfined
    - label=disable
  environment: &x-engine-env
    #LLAMA_CACHE: /models
    GGML_VERBOSE: 1
    # Jesse: Do NOT set `HSA_OVERRIDE_GFX_VERSION` - causes kernel mismatches on Strix Halo
    #HSA_OVERRIDE_GFX_VERSION: 11.0.2
    ROCBLAS_LAYER: 4
    # Jesse: in ROCm containers to prevent DMA issues
    HSA_ENABLE_SDMA: 0
    LLAMA_ARG_MODEL: /huggingface/hub/models--bartowski--kldzj_gpt-oss-120b-heretic-GGUF/snapshots/406292f67859a86dd34853c75b573aadedf6cbda/kldzj_gpt-oss-120b-heretic-bf16/kldzj_gpt-oss-120b-heretic-bf16-00001-of-00002.gguf
  volumes:
    #- ./models:/models:Z
    - ~/.cache/huggingface:/huggingface:ro

x-engine-vulkan-radv: &x-engine-vulkan-radv
  <<: *x-engine
  image: berne/amd-strix-halo-toolboxes:vulkan-radv
  build:
    context: amd-strix-halo-toolboxes
    args:
      TAG: vulkan-radv

x-engine-vulkan-amdvlk: &x-engine-vulkan-amdvlk
  <<: *x-engine
  image: berne/amd-strix-halo-toolboxes:vulkan-amdvlk
  build:
    context: amd-strix-halo-toolboxes
    args:
      TAG: vulkan-amdvlk

x-engine-rocm-6.4.4: &x-engine-rocm-6.4.4
  <<: *x-engine
  image: berne/amd-strix-halo-toolboxes:rocm-6.4.4
  build:
    context: amd-strix-halo-toolboxes
    args:
      TAG: rocm-6.4.4

x-engine-rocm-7.2: &x-engine-rocm-7.2
  <<: *x-engine
  image: berne/amd-strix-halo-toolboxes:rocm-7.2
  build:
    context: amd-strix-halo-toolboxes
    args:
      TAG: rocm-7.2

x-engine-rocm7-nightlies: &x-engine-rocm7-nightlies
  <<: *x-engine
  image: berne/amd-strix-halo-toolboxes:rocm7-nightlies
  build:
    context: amd-strix-halo-toolboxes
    args:
      TAG: rocm7-nightlies

x-model: &x-model
  # FML not all arguments have env var equivalents: warmup, temp, top-p, min-p, typical
  command: >-
    llama-server
    --no-warmup
    --temp 0.3
    --top-p 0.95
    --min-p 0.05
    --typical 0.95
  environment: &x-model-env
    LLAMA_ARG_FLASH_ATTN: auto
    LLAMA_ARG_HOST: 0.0.0.0
    LLAMA_ARG_CONT_BATCHING: on
    LLAMA_ARG_N_PARALLEL: 1
    LLAMA_ARG_N_GPU_LAYERS: all
    LLAMA_ARG_CONTEXT_SHIFT: on
    LLAMA_ARG_CTX_SIZE: 32768

x-model-benchmark: &x-model-benchmark
  <<: *x-model
  # Use wrapper so we can use env var LLAMA_ARG_MODEL
  command: >-
    llama-bench-wrapper
    -ngl 999
    --no-warmup
    --flash-attn on
    -p 512,1024,2048
    -n 128

x-model-vulkan-radv: &x-model-vulkan-radv
  <<: [*x-model, *x-engine-vulkan-radv]
  profiles:
    - model
    - vulkan-radv
  environment: &x-model-vulkan-radv-env
    <<: [*x-model-env, *x-engine-env]

x-model-vulkan-amdvlk: &x-model-vulkan-amdvlk
  <<: [*x-model, *x-engine-vulkan-amdvlk]
  profiles:
    - model
    - vulkan-amdvlk
  environment: &x-model-vulkan-amdvlk-env
    <<: [*x-model-env, *x-engine-env]

x-model-rocm-6.4.4: &x-model-rocm-6.4.4
  <<: [*x-model, *x-engine-rocm-6.4.4]
  profiles:
    - model
    - rocm-6.4.4
  environment: &x-model-rocm-6.4.4-env
    <<: [*x-model-env, *x-engine-env]

x-model-rocm-7.2: &x-model-rocm-7.2
  <<: [*x-model, *x-engine-rocm-7.2]
  profiles:
    - model
    - rocm-7.2
  environment: &x-model-rocm-7.2-env
    <<: [*x-model-env, *x-engine-env]

x-model-rocm7-nightlies: &x-model-rocm7-nightlies
  <<: [*x-model, *x-engine-rocm7-nightlies]
  profiles:
    - model
    - rocm7-nightlies
  environment: &x-model-rocm7-nightlies-env
    <<: [*x-model-env, *x-engine-env]

x-model-benchmark-vulkan-radv: &x-model-benchmark-vulkan-radv
  <<: [*x-model-benchmark, *x-engine-vulkan-radv]
  profiles:
    - benchmark
    - vulkan-radv
  environment: &x-model-benchmark-vulkan-radv-env
    <<: [*x-model-env, *x-engine-env]

x-model-benchmark-vulkan-amdvlk: &x-model-benchmark-vulkan-amdvlk
  <<: [*x-model-benchmark, *x-engine-vulkan-radv]
  profiles:
    - benchmark
    - vulkan-radv
  environment: &x-model-benchmark-vulkan-amdvlk-env
    <<: [*x-model-env, *x-engine-env]

x-model-benchmark-rocm-6.4.4: &x-model-benchmark-rocm-6.4.4
  <<: [*x-model-benchmark, *x-engine-rocm-6.4.4]
  profiles:
    - benchmark
    - rocm-6.4.4
  environment: &x-model-benchmark-rocm-6.4.4-env
    <<: [*x-model-env, *x-engine-env]

x-model-benchmark-rocm-7.2: &x-model-benchmark-rocm-7.2
  <<: [*x-model-benchmark, *x-engine-rocm-7.2]
  profiles:
    - benchmark
    - rocm-7.2
  environment: &x-model-benchmark-rocm-7.2-env
    <<: [*x-model-env, *x-engine-env]

x-model-benchmark-rocm7-nightlies: &x-model-benchmark-rocm7-nightlies
  <<: [*x-model-benchmark, *x-engine-rocm7-nightlies]
  profiles:
    - benchmark
    - rocm7-nightlies
  environment: &x-model-benchmark-rocm7-nightlies-env
    <<: [*x-model-env, *x-engine-env]


volumes:
  openwebui-data:
  perplexica-uploads:

services:
  searxng:
    profiles:
      # implicit default
      - ""
    image: docker.io/searxng/searxng:latest
    #container_name: searxng
    ports:
      - "8185:8080"
    volumes:
      - ./searxng:/etc/searxng:Z
    #restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/sbin/wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  perplexica:
    profiles:
      # implicit default
      - ""
    # tag `latest` has a builtin SearxNG
    # tag `slim-latest` doesn't
    image: docker.io/itzcrazykns1337/perplexica:slim-latest
    #container_name: perplexica
    #network_mode: host
    volumes:
      - ./perplexica/data:/home/perplexica/data:Z
      - perplexica-uploads:/home/perplexica/uploads:Z
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - PORT=3001
      - HOSTNAME=0.0.0.0
    #restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - searxng
      - llama-swap

  llama-swap:
    profiles:
      # implicit default
      - ""
    # vulkan for AMD Strix Halo
    build: llama-swap
    #image: ghcr.io/mostlygeek/llama-swap:vulkan-non-root
    image: berne/llama-swap:vulkan-non-root
    #user: "1000:1000"
    userns_mode: keep-id
    # This is `ubuntu` user rather than `app` user.
    # Same UID as me, so my podman socket should work.
    #user: "1000:1000"
    user: bdawg
    environment:
      #HOME: /home/ubuntu
      HOME: /home/bdawg
      CONTAINER_HOST: unix:///run/user/1000/podman/podman.sock
    # configuration hot reload supported with a directory volume mount
    #command: >-
    #  -config /config/config.yaml
    #  -watch-config
    #image: ghcr.io/mostlygeek/llama-swap:vulkan-non-root
    devices:
      # Direct Rendering Infrastructure (dri) - exposes renderer nodes (renderD128) and compute shaders, used by Vulkan/Mesa
      - /dev/dri:/dev/dri
      # Kernel Fusion Driver (kfd) - primary compute interface - essential for HIP/ROCm
      - /dev/kfd:/dev/kfd
    group_add:
      # Unable to find group render: no matching entries in group file
      #- render
      - video
      - app
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - label=disable
    ports:
      - 8090:8080
    working_dir: /genai-mei
    command: llama-swap -config config.yaml
    volumes:
      - ./llama-swap/config.yaml:/app/config.yaml:Z
    #  - ./config:/config
      - ${XDG_RUNTIME_DIR}/podman:/run/user/1000/podman:Z
      # The parent directory needs to match the host as docker-compose bases the container names off it
      - ./docker-compose.yml:/genai-mei/docker-compose.yml:ro
      #- ./models:/models:Z
      # Don't needed to mount as podman (compose) is doing bind mounts from hosts point of view
      # But the `~` in the docker-compose.yml (this file) should match in the container and host (e.g. `bdawg`)
      #- ~/.cache/huggingface:/huggingface:ro


  # Not really needed, llama-server has a build in web UI that's nearly as good.
  # OpenWebUI takes about 813MiB of RAM
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    profiles:
      - open-webui
    #network_mode: host
    #container_name: open-webui
    ports:
      - 8080:8080
    volumes:
      - openwebui-data:/app/backend/data:Z
    environment:
      #OPENAI_API_BASE_URLS: http://localhost:8090/v1
      OPENAI_API_BASE_URLS: http://llama-swap:8080/v1
      OPENAI_API_KEYS: sk-llamaswap
      #RAG_EMBEDDING_ENGINE: openai
      #RAG_EMBEDDING_MODEL: bge-embed
      #RAG_OPENAI_API_BASE_URL: http://localhost:8090/v1
      #RAG_OPENAI_API_KEY: sk-llamaswap
      #RAG_RERANKING_ENGINE: external
      #RAG_RERANKING_MODEL: bge-rerank
      #RAG_EXTERNAL_RERANKER_URL: http://localhost:10002/v1/rerank
      #RAG_EXTERNAL_RERANKER_API_KEY: sk-llamaswap
      #ENABLE_RAG_WEB_SEARCH: "true"
      #RAG_WEB_SEARCH_ENGINE: searxng
      #SEARXNG_QUERY_URL: http://localhost:8085/search?q=<query>
      ENABLE_OLLAMA_API: "false"
      # Speech to Text (STT)
      #AUDIO_STT_ENGINE: openai
      #AUDIO_STT_OPENAI_API_BASE_URL: http://llama-swap:8080/v1
      #AUDIO_STT_OPENAI_API_KEYS: sk-llamaswap
    #restart: unless-stopped
    #depends_on:
    #  - llama-swap


  # huggingface CLI
  # Use to download models
  facehugger:
    userns_mode: keep-id
    profiles:
      - facehugger
      - bootstrap
    image: berne/facehugger
    entrypoint: facehugger
    command: ""
    #command: [""]
    #command: >-
    #  hf download bartowski/kldzj_gpt-oss-120b-heretic-GGUF/tree/main/kldzj_gpt-oss-120b-heretic-bf16
    volumes:
      - ~/.cache/huggingface:/home/bdawg/.cache/huggingface:Z
      - ./facehugger/facehugger.yaml:/facehugger.yaml


  mistral-vibe:
    profiles:
      - mistral-vibe
    build: mistral-vibe
    image: berne/mistral-vibe


  # --------------------------------------------------------------------------------
  # Models
  # --------------------------------------------------------------------------------

  # large uncensored model
  # BF16 Quant
  # bdawg: Would Q8_0 be better? The GPU has bf16: 0
  #        Ah this depends on the inference runtime (engine) - amdvlk should have bf16: 1
  heretic-gpt-oss-120b: &heretic-gpt-oss-120b
    <<: *x-model-vulkan-radv
    #profiles:
    #  - model-heretic-gpt-oss-120b
    environment: &heretic-gpt-oss-120b-env
      <<: *x-model-vulkan-radv-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--bartowski--kldzj_gpt-oss-120b-heretic-GGUF/snapshots/406292f67859a86dd34853c75b573aadedf6cbda/kldzj_gpt-oss-120b-heretic-bf16/kldzj_gpt-oss-120b-heretic-bf16-00001-of-00002.gguf
    ports:
      - 8120:8080

  heretic-gpt-oss-120b-benchmark:
    <<: *x-model-benchmark-vulkan-radv
    environment:
      <<: *heretic-gpt-oss-120b-env

  heretic-gpt-oss-120b-vulkan-amdvlk:
    # Merge precedence is (preferred) parent, first, to last.
    # Once a field is set any dupes are ignored.
    <<: [*x-model-vulkan-amdvlk, *heretic-gpt-oss-120b]
    # x-model-vulkan-amdvlk sets environ
    # So we need to override it here
    environment:
      <<: *heretic-gpt-oss-120b-env

  heretic-gpt-oss-120b-vulkan-amdvlk-benchmark:
    <<: *x-model-benchmark-vulkan-amdvlk
    environment:
      <<: *heretic-gpt-oss-120b-env

  heretic-gpt-oss-120b-rocm-6.4.4:
    # Merge precedence is (preferred) parent, first, to last.
    # Once a field is set any dupes are ignored.
    <<: [*x-model-rocm-6.4.4, *heretic-gpt-oss-120b]
    # x-model-base-vulkan-amdvlk inherits model-base that sets environ
    # So we need to override it here
    environment:
      <<: *heretic-gpt-oss-120b-env

  heretic-gpt-oss-120b-rocm-6.4.4-benchmark:
    <<: *x-model-benchmark-rocm-6.4.4
    environment:
      <<: *heretic-gpt-oss-120b-env

  heretic-gpt-oss-120b-rocm-7.2:
    # Merge precedence is (preferred) parent, first, to last.
    # Once a field is set any dupes are ignored.
    <<: [*x-model-rocm-7.2, *heretic-gpt-oss-120b]
    # x-model-base-vulkan-amdvlk inherits model-base that sets environ
    # So we need to override it here
    environment:
      <<: *heretic-gpt-oss-120b-env

  heretic-gpt-oss-120b-rocm-7.2-benchmark:
    <<: *x-model-benchmark-rocm-7.2
    environment:
      <<: *heretic-gpt-oss-120b-env

  heretic-gpt-oss-120b-rocm7-nightlies:
    # Merge precedence is (preferred) parent, first, to last.
    # Once a field is set any dupes are ignored.
    <<: [*x-model-rocm7-nightlies, *heretic-gpt-oss-120b]
    # x-model-base-vulkan-amdvlk inherits model-base that sets environ
    # So we need to override it here
    environment:
      <<: *heretic-gpt-oss-120b-env

  heretic-gpt-oss-120b-rocm7-nightlies-benchmark:
    <<: *x-model-benchmark-rocm7-nightlies
    environment:
      <<: *heretic-gpt-oss-120b-env


  # Quannt Q8_0
  heretic-gpt-oss-120b-q8:
    <<: *x-model-vulkan-radv
    #profiles:
    #  - model-heretic-gpt-oss-120b-q8
    environment: &heretic-gpt-oss-120b-q8-env
      <<: *x-model-vulkan-radv-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--bartowski--kldzj_gpt-oss-120b-heretic-GGUF/snapshots/406292f67859a86dd34853c75b573aadedf6cbda/kldzj_gpt-oss-120b-heretic-Q8_0/kldzj_gpt-oss-120b-heretic-Q8_0-00001-of-00002.gguf
      # default is 8080
      #LLAMA_ARG_PORT: 8120
    ports:
      - 8121:8080

  heretic-gpt-oss-120b-q8-benchmark:
    <<: *x-model-benchmark-vulkan-radv
    environment:
      <<: *heretic-gpt-oss-120b-q8-env

  qwen-coder-30b:
    <<: *x-model-vulkan-radv
    environment: &qwen-coder-30b-env
      <<: *x-model-vulkan-radv-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--Qwen3-Coder-30B-A3B-Instruct-GGUF/snapshots/7ce945e58ed3f09f9cf9c33a2122d86ac979b457/Qwen3-Coder-30B-A3B-Instruct-Q8_0.gguf
      #LLAMA_ARG_PORT: 8130
    ports:
      - 8130:8080

  qwen-coder-30b-benchmark:
    <<: *x-model-benchmark-vulkan-radv
    environment:
      <<: *qwen-coder-30b-env

  qwen3-4b-128k-q6:
    <<: *x-model-vulkan-radv
    environment: &qwen3-4b-128k-q6-env
      <<: *x-model-vulkan-radv-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--Qwen3-4B-128K-GGUF/snapshots/a21842b9582c3888b30568b8e84afe533275f646/Qwen3-4B-128K-UD-Q6_K_XL.gguf
      #LLAMA_ARG_PORT: 8140
    ports:
      - 8140:8080

  qwen3-4b-128k-q6-benchmark:
    <<: *x-model-benchmark-vulkan-radv
    environment:
      <<: *qwen3-4b-128k-q6-env

  qwen3-4b-128k-q8:
    <<: *x-model-vulkan-radv
    environment: &qwen3-4b-128k-q8-env
      <<: *x-model-vulkan-radv-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--Qwen3-4B-128K-GGUF/snapshots/a21842b9582c3888b30568b8e84afe533275f646/Qwen3-4B-128K-UD-Q8_K_XL.gguf
      #LLAMA_ARG_PORT: 8150
    ports:
      - 8150:8080

  qwen3-4b-128k-q8-benchmark:
    <<: *x-model-benchmark-vulkan-radv
    environment:
      <<: *qwen3-4b-128k-q8-env

  # primary coding model
  glm-4.7-flash:
    <<: *x-model-vulkan-radv
    command: &coder-env >-
      llama-server
      --no-warmup
      --temp 0.3
      --top-p 1.0
      --min-p 0.01
      --typical 0.95
      --repeat-penalty 1.0
    environment: &glm-47-flash-env
      <<: *x-model-vulkan-radv-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--GLM-4.7-Flash-GGUF/snapshots/66205ea11ef638d83850389bd921e6c199f7504e/GLM-4.7-Flash-UD-Q8_K_XL.gguf
      #LLAMA_ARG_PORT: 8160
      LLAMA_ARG_CTX_SIZE: 202752
    ports:
      - 8160:8080

  glm-4.7-flash-benchmark:
    <<: *x-model-benchmark-vulkan-radv
    # No env vars for several options
    # https://unsloth.ai/docs/models/glm-4.7-flash
    environment:
      <<: *glm-47-flash-env
