# extensions
# https://docs.docker.com/reference/compose-file/extension/
# Prefixed these with `x-`

# Inference Engines (Runtimes)
x-engine: &x-engine
  devices:
    # Direct Rendering Infrastructure (dri) - exposes renderer nodes (renderD128) and compute shaders, used by Vulkan/Mesa
    - /dev/dri:/dev/dri
    # Kernel Fusion Driver (kfd) - primary compute interface - essential for HIP/ROCm
    - /dev/kfd:/dev/kfd
  group_add:
    - render
    - video
  security_opt:
    - seccomp:unconfined
    - apparmor:unconfined
    - label=disable
  environment: &x-engine-env
    #LLAMA_CACHE: /models
    GGML_VERBOSE: 1
    # Jesse: Do NOT set `HSA_OVERRIDE_GFX_VERSION` - causes kernel mismatches on Strix Halo
    #HSA_OVERRIDE_GFX_VERSION: 11.0.2
    ROCBLAS_LAYER: 4
    # Jesse: in ROCm containers to prevent DMA issues
    HSA_ENABLE_SDMA: 0
  volumes:
    #- ./models:/models:Z
    - ~/.cache/huggingface:/huggingface:ro

x-engine-rocm-723: &x-engine-rocm-723
  <<: *x-engine
  image: berne/amd-strix-halo-toolboxes:rocm-7.2.3
  build:
    context: amd-strix-halo-toolboxes
    args:
      TAG: rocm-7.2.3

x-engine-rocm-724: &x-engine-rocm-724
  <<: *x-engine
  image: berne/amd-strix-halo-toolboxes:rocm-7.2.4
  build:
    context: amd-strix-halo-toolboxes
    args:
      TAG: rocm-7.2.4

x-engine-rocm-7-14: &x-engine-rocm-7-14
  <<: *x-engine
  image: berne/amd-strix-halo-toolboxes:rocm-7.14
  build:
    context: amd-strix-halo-toolboxes
    args:
      TAG: rocm-7.14

x-model: &x-model
  # FML not all arguments have env var equivalents: warmup, temp, top-p, min-p, typical
  command: >-
    llama-server
    --no-warmup
    --temp 0.3
    --top-p 0.95
    --min-p 0.05
    --typical 0.95
  environment: &x-model-env
    LLAMA_ARG_FLASH_ATTN: auto
    LLAMA_ARG_HOST: 0.0.0.0
    #LLAMA_ARG_CONT_BATCHING: on
    #LLAMA_ARG_N_PARALLEL: 1
    LLAMA_ARG_N_GPU_LAYERS: all
    #LLAMA_ARG_CONTEXT_SHIFT: on
    #LLAMA_ARG_CTX_SIZE: 32768

x-model-benchmark: &x-model-benchmark
  <<: *x-model
  # Use wrapper so we can use env var LLAMA_ARG_MODEL
  command: >-
    llama-bench-wrapper
    -ngl 999
    --no-warmup
    --flash-attn on
    -p 512,1024,2048
    -n 128
    -o json
    -oe md
  #  -o jsonl

x-model-rocm-723: &x-model-rocm-723
  <<: [*x-model, *x-engine-rocm-723]
  profiles:
    - model
    - rocm-7.2.3
  environment: &x-model-rocm-723-env
    <<: [*x-model-env, *x-engine-env]

x-model-rocm-724: &x-model-rocm-724
  <<: [*x-model, *x-engine-rocm-724]
  profiles:
    - model
    - rocm-7.2.4
  environment: &x-model-rocm-724-env
    <<: [*x-model-env, *x-engine-env]

x-model-rocm-7-14: &x-model-rocm-7-14
  <<: [*x-model, *x-engine-rocm-7-14]
  profiles:
    - model
    - rocm-7.14
  environment: &x-model-rocm-7-14-env
    <<: [*x-model-env, *x-engine-env]

x-model-benchmark-rocm-723: &x-model-benchmark-rocm-723
  <<: [*x-model-benchmark, *x-engine-rocm-723]
  profiles:
    - benchmark
    - rocm-7.2.3
  environment: &x-model-benchmark-rocm-723-env
    <<: [*x-model-env, *x-engine-env]

x-model-benchmark-rocm-724: &x-model-benchmark-rocm-724
  <<: [*x-model-benchmark, *x-engine-rocm-724]
  profiles:
    - benchmark
    - rocm-7.2.4
  environment: &x-model-benchmark-rocm-724-env
    <<: [*x-model-env, *x-engine-env]

x-model-benchmark-rocm-7-14: &x-model-benchmark-rocm-7-14
  <<: [*x-model-benchmark, *x-engine-rocm-7-14]
  profiles:
    - benchmark
    - rocm-7.14
  environment: &x-model-benchmark-rocm-7-14-env
    <<: [*x-model-env, *x-engine-env]


volumes:
  openwebui-data:
  vane-uploads:

services:
  searxng:
    profiles:
      # implicit default
      - ""
    image: docker.io/searxng/searxng:latest
    #container_name: searxng
    ports:
      - "8185:8080"
    volumes:
      - ./searxng:/etc/searxng:Z
    restart: no
    env_file: .env/searxng.env
    healthcheck:
      test: ["CMD", "/usr/sbin/wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

  # new name of perplexica
  vane:
    profiles:
      # implicit default
      - ""
    # tag `latest` has a builtin SearxNG
    # tag `slim-latest` doesn't
    image: docker.io/itzcrazykns1337/vane:slim-latest
    volumes:
      - ./vane/data:/home/vane/data:Z
      - vane-uploads:/home/vane/uploads:Z
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - PORT=3001
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - searxng
      - llama-swap

  llama-swap:
    profiles:
      # implicit default
      - ""
    build: llama-swap
    image: berne/llama-swap:rocm-non-root
    #user: "1000:1000"
    userns_mode: keep-id
    # This is `ubuntu` user rather than `app` user.
    # Same UID as me, so my podman socket should work.
    #user: "1000:1000"
    user: bdawg
    environment:
      #HOME: /home/ubuntu
      HOME: /home/bdawg
      CONTAINER_HOST: unix:///run/user/1000/podman/podman.sock
    # configuration hot reload supported with a directory volume mount
    #command: >-
    #  -config /config/config.yaml
    #  -watch-config
    devices:
      # Direct Rendering Infrastructure (dri) - exposes renderer nodes (renderD128) and compute shaders, used by Vulkan/Mesa
      - /dev/dri:/dev/dri
      # Kernel Fusion Driver (kfd) - primary compute interface - essential for HIP/ROCm
      - /dev/kfd:/dev/kfd
    group_add:
      # Unable to find group render: no matching entries in group file
      #- render
      - video
      - app
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - label=disable
    ports:
      - 8090:8080
    restart: unless-stopped
    working_dir: /genai-mei
    command: llama-swap -config config.yaml
    volumes:
      - ./llama-swap/config.yaml:/app/config.yaml:Z
    #  - ./config:/config
      - ${XDG_RUNTIME_DIR}/podman:/run/user/1000/podman:Z
      # The parent directory needs to match the host as docker-compose bases the container names off it
      - ./docker-compose.yml:/genai-mei/docker-compose.yml:ro
      #- ./models:/models:Z
      # Don't needed to mount as podman (compose) is doing bind mounts from hosts point of view
      # But the `~` in the docker-compose.yml (this file) should match in the container and host (e.g. `bdawg`)
      #- ~/.cache/huggingface:/huggingface:ro


  # Not really needed, llama-server has a build in web UI that's nearly as good.
  # But Conduit is made to work with Open WebUI
  # And I got full duplex voice conversations (STT->Reason->TTS) working in Open WebUI
  # OpenWebUI takes about 813MiB of RAM
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    #image: berne/open-webui
    profiles:
      # implicit default
      - ""
    ports:
      - 8080:8080
    volumes:
      - openwebui-data:/app/backend/data:Z
    environment:
      #OPENAI_API_BASE_URLS: http://localhost:8090/v1
      OPENAI_API_BASE_URLS: http://llama-swap:8080/v1
      OPENAI_API_KEYS: sk-llamaswap
      #RAG_EMBEDDING_ENGINE: openai
      #RAG_EMBEDDING_MODEL: bge-embed
      #RAG_OPENAI_API_BASE_URL: http://localhost:8090/v1
      #RAG_OPENAI_API_KEY: sk-llamaswap
      #RAG_RERANKING_ENGINE: external
      #RAG_RERANKING_MODEL: bge-rerank
      #RAG_EXTERNAL_RERANKER_URL: http://localhost:10002/v1/rerank
      #RAG_EXTERNAL_RERANKER_API_KEY: sk-llamaswap
      #ENABLE_RAG_WEB_SEARCH: "true"
      #RAG_WEB_SEARCH_ENGINE: searxng
      #SEARXNG_QUERY_URL: http://localhost:8085/search?q=<query>
      ENABLE_OLLAMA_API: "false"
      # Speech to Text (STT)
      #AUDIO_STT_ENGINE: openai
      #AUDIO_STT_OPENAI_API_BASE_URL: http://llama-swap:8080/v1
      #AUDIO_STT_OPENAI_API_KEYS: sk-llamaswap
    restart: unless-stopped
    #depends_on:
    #  - llama-swap

  #context7-mcp:
  #  image: berne/context7-mcp
  #  profiles:
  #    # implicit default
  #    - ""
  #  ports:
  #    - 3000:3000


  # ==============================================================================================================================================================
  # whisper.cpp
  # ==============================================================================================================================================================
  whisper.cpp:
    profiles:
      - whisper
    # main-rocm tag doesn't exist - this was a local build where I didn't change the FQ name
    #image: ghcr.io/ggml-org/whisper.cpp:main-rocm
    #image: ghcr.io/ggml-org/whisper.cpp:main-vulkan
    image: ghcr.io/ggml-org/whisper.cpp:main-vulkan-306c88f4d1286aec1bf96e544632897886af5501
    #image: berne/whisper.cpp:main-vulkan
    #image: berne/whisper.cpp:main-rocm
    userns_mode: keep-id
    # Command Line
    # - entrypoint is `bash -c` so need the quotes
    # - need to listen on 0.0.0.0 so host can connect to docker published port
    # - OpenAPI Compatibility set request path and inference path
    #   https://github.com/mostlygeek/llama-swap/issues/41#issuecomment-2722637867
    command: >-
      "whisper-server --host 0.0.0.0 -m /models/ggml-large-v3-turbo-q5_0.bin --request-path /v1/audio/transcriptions --inference-path '' --vad --vad-model /models/ggml-silero-v6.2.0.bin"
    #  "whisper-server --host 0.0.0.0 -m /models/ggml-large-v3-turbo-q5_0.bin --request-path /v1/audio/transcriptions --inference-path ''"
    #  "whisper-server --host 0.0.0.0 -m /models/ggml-large-v3-turbo-q5_0.bin"
    #  "whisper-server --host 0.0.0.0 -m /models/ggml-base.en.bin"
    #  "whisper-server --host 0.0.0.0 -m /models/ggml-large-v3.bin"
    devices:
      # Direct Rendering Infrastructure (dri) - exposes renderer nodes (renderD128) and compute shaders, used by Vulkan/Mesa
      - /dev/dri:/dev/dri
      # Kernel Fusion Driver (kfd) - primary compute interface - essential for HIP/ROCm
      - /dev/kfd:/dev/kfd
    #group_add:
    #  - video
    restart: never
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - label=disable
    ports:
      - "8999:8080"
    #working_dir: /genai-mei
    volumes:
      # From host's perspecitve
      #- ./whisper-models:/models:Z
      # From llama-swap's perspective
      #- /tmp/whisper-models:/models:Z
      #
      # Podman CLI (client-side) will create the source directory if it doesn't exist (think inside the llama-swap container)
      # So, the parent directory chain needs to be R/W.
      # The actual mount will happen on the host (podman daemon listening on the socket)
      # So, we give a source path that is both correct from hosts POV and writable from llama-servers POV
      - ~/genai/genai-mei/whisper-models:/models:ro

  whisper-bench:
    profiles:
      - whisper-bench
    # main-rocm tag doesn't exist - this was a local build where I didn't change the FQ name
    #image: ghcr.io/ggml-org/whisper.cpp:main-rocm
    image: ghcr.io/ggml-org/whisper.cpp:main-vulkan
    userns_mode: keep-id
    # entrypoint is `bash -c` so need the quotes
    # need to listen on 0.0.0.0 so host can connect to docker published port
    #command: >-
    #  "whisper-server --host 0.0.0.0 -m /models/ggml-base.en.bin"
    command: >-
      "whisper-bench -m /models/ggml-large-v3-turbo-q5_0.bin -t 8"
    #  "whisper-bench -m /models/ggml-small.en.bin -t 4"
    #  "whisper-bench -m /models/ggml-large-v3.bin -t 8"
    #  "whisper-bench -m /models/ggml-large-v3-turbo.bin -t 8"
    #  "whisper-bench -m /models/ggml-large-v3-turbo-q8_0.bin -t 8"
    devices:
      # Direct Rendering Infrastructure (dri) - exposes renderer nodes (renderD128) and compute shaders, used by Vulkan/Mesa
      - /dev/dri:/dev/dri
      # Kernel Fusion Driver (kfd) - primary compute interface - essential for HIP/ROCm
      - /dev/kfd:/dev/kfd
    #group_add:
    #  - video
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - label=disable
    #working_dir: /genai-mei
    volumes:
      # From host's perspecitve
      - ./whisper-models:/models:Z
      # From llama-swap's perspective
      #- /whisper-models:/models:Z

  whisper-download:
    profiles:
      - whisper-download
    image: ghcr.io/ggml-org/whisper.cpp:main-rocm
    userns_mode: keep-id
    # entrypoint is `bash -c` so need the quotes
    volumes:
      - ./whisper-models:/models:Z
    command: >-
      "./models/download-vad-model.sh silero-v6.2.0 /models"
    #  "./models/download-ggml-model.sh base /models"
    #  "./models/download-ggml-model.sh base.en /models"
    #  "./models/download-ggml-model.sh small /models"
    #  "./models/download-ggml-model.sh small.en /models"
    #  "./models/download-ggml-model.sh small.en-tdrz /models"
    #  "./models/download-ggml-model.sh medium /models"
    #  "./models/download-ggml-model.sh medium.en /models"
    #  "./models/download-ggml-model.sh large-v3 /models"
    #  "./models/download-ggml-model.sh large-v3-turbo /models"
    #  "./models/download-ggml-model.sh large-v3-turbo-q8_0 /models"
    #  "./models/download-ggml-model.sh large-v3-turbo-q5_0 /models"

  # ==============================================================================================================================================================
  # huggingface CLI
  # ==============================================================================================================================================================
  # Use to download models
  facehugger:
    profiles:
      - facehugger
      - bootstrap
    userns_mode: keep-id
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
      - label=disable
    image: berne/facehugger
    entrypoint: facehugger
    command: ""
    #command: >-
    #  hf download bartowski/kldzj_gpt-oss-120b-heretic-GGUF/tree/main/kldzj_gpt-oss-120b-heretic-bf16
    volumes:
      - ~/.cache/huggingface:/home/bdawg/.cache/huggingface:Z
      - ./facehugger/facehugger.yaml:/facehugger.yaml


  # ====================================================================================================================================
  # Models
  # ====================================================================================================================================



  # --------------------------------------------------------------------------------------------------------------------------------
  qwen36-35B-A3B: &qwen36-35B-A3B
    <<: *x-model-rocm-7-14
    environment: &qwen36-35B-A3B-env
      <<: *x-model-rocm-7-14-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--Qwen3.6-35B-A3B-GGUF/snapshots/a483e9e6cbd595906af30beda3187c2663a1118c/Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf
      LLAMA_ARG_CONT_BATCHING: off
      # llama.cpp default is 40, unsloth guide recommends 20
      LLAMA_ARG_TOP_K: 20
    ports:
      - 8140:8080
    command: >-
      llama-server
      --no-warmup
      --temp 1.0
      --presence-penalty 1.5
      --mmproj /huggingface/hub/models--unsloth--Qwen3.6-35B-A3B-GGUF/snapshots/a483e9e6cbd595906af30beda3187c2663a1118c/mmproj-BF16.gguf
    #  --top-p 0.95 (default)
    #  --repeat-penalty 1.0 (default)
    #  --typical 0.95 (default is 1.0)

  qwen36-35B-A3B-MTP: &qwen36-35B-A3B-MTP
    <<: *x-model-rocm-7-14
    environment: &qwen36-35B-A3B-MTP-env
      <<: *x-model-rocm-7-14-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--Qwen3.6-35B-A3B-MTP-GGUF/snapshots/b8efbbece76dc9103a6a45b7ed95b26c3932fc5f/Qwen3.6-35B-A3B-UD-Q8_K_XL.gguf
      LLAMA_ARG_CONT_BATCHING: off
      # llama.cpp default is 40, unsloth guide recommends 20
      LLAMA_ARG_TOP_K: 20
    ports:
      - 8140:8080
    command: >-
      llama-server
      --no-warmup
      --temp 1.0
      --presence-penalty 1.5
      --mmproj /huggingface/hub/models--unsloth--Qwen3.6-35B-A3B-MTP-GGUF/snapshots/b8efbbece76dc9103a6a45b7ed95b26c3932fc5f/mmproj-BF16.gguf
      --spec-type draft-mtp
    # ben: default is 3, 3 seems the best
    #  --spec-draft-n-max 16

  qwen36-35B-A3B-coding: &qwen36-35B-A3B-coding
    <<: *qwen36-35B-A3B
    command: >-
      llama-server
      --no-warmup
      --temp 0.6
    #  --presence-penalty 0.00 (default)

  qwen36-35B-A3B-rocm-723-benchmark:
    <<: *x-model-benchmark-rocm-723
    environment:
      <<: *qwen36-35B-A3B-env

  qwen36-35B-A3B-rocm-724-benchmark:
    <<: *x-model-benchmark-rocm-724
    environment:
      <<: *qwen36-35B-A3B-env

  qwen36-35B-A3B-rocm-7-14-benchmark:
    <<: *x-model-benchmark-rocm-7-14
    environment:
      <<: *qwen36-35B-A3B-env


  # Qwen3.6 35B A3B MTP
  qwen36-35B-A3B-MTP-rocm-723-benchmark:
    <<: *x-model-benchmark-rocm-723
    environment:
      <<: *qwen36-35B-A3B-MTP-env

  qwen36-35B-A3B-MTP-rocm-724-benchmark:
    <<: *x-model-benchmark-rocm-724
    environment:
      <<: *qwen36-35B-A3B-MTP-env

  qwen36-35B-A3B-MTP-rocm-7-14-benchmark:
    <<: *x-model-benchmark-rocm-7-14
    environment:
      <<: *qwen36-35B-A3B-MTP-env


  # --------------------------------------------------------------------------------------------------------------------------------------------------------------
  qwen36-27B: &qwen36-27B
    <<: *x-model-rocm-7-14
    environment: &qwen36-27B-env
      <<: *x-model-rocm-7-14-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--Qwen3.6-27B-GGUF/snapshots/82d411acf4a06cfb8d9b073a5211bf410bfc29bf/Qwen3.6-27B-UD-Q8_K_XL.gguf
      LLAMA_ARG_CONT_BATCHING: off
      # llama.cpp default is 40, unsloth guide recommends 20
      LLAMA_ARG_TOP_K: 20
    ports:
      - 8140:8080
    command: >-
      llama-server
      --no-warmup
      --temp 1.0
      --presence-penalty 1.5
      --mmproj /huggingface/hub/models--unsloth--Qwen3.6-35B-A3B-GGUF/snapshots/82d411acf4a06cfb8d9b073a5211bf410bfc29bf/mmproj-BF16.gguf

  qwen36-27B-MTP: &qwen36-27B-MTP
    <<: *x-model-rocm-7-14
    environment: &qwen36-27B-MTP-env
      <<: *x-model-rocm-7-14-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--Qwen3.6-27B-MTP-GGUF/snapshots/0da008d9b980b76520a952bb3aa4abbaa0955647/Qwen3.6-27B-UD-Q8_K_XL.gguf
      LLAMA_ARG_CONT_BATCHING: off
      # llama.cpp default is 40, unsloth guide recommends 20
      LLAMA_ARG_TOP_K: 20
    ports:
      - 8140:8080
    command: >-
      llama-server
      --no-warmup
      --temp 1.0
      --presence-penalty 1.5
      --mmproj /huggingface/hub/models--unsloth--Qwen3.6-35B-A3B-GGUF/snapshots/0da008d9b980b76520a952bb3aa4abbaa0955647/mmproj-BF16.gguf
      --spec-type draft-mtp
    # --spec-draft-n-max 3
    # # (default is 3)

  qwen36-27B-rocm-723-benchmark:
    <<: *x-model-benchmark-rocm-723
    environment:
      <<: *qwen36-27B-env

  qwen36-27B-rocm-724-benchmark:
    <<: *x-model-benchmark-rocm-724
    environment:
      <<: *qwen36-27B-env

  qwen36-27B-rocm-7-14-benchmark:
    <<: *x-model-benchmark-rocm-7-14
    environment:
      <<: *qwen36-27B-env


  # Qwen3.6 27B MTP
  qwen36-27B-MTP-rocm-723-benchmark:
    <<: *x-model-benchmark-rocm-723
    environment:
      <<: *qwen36-27B-MTP-env

  qwen36-27B-MTP-rocm-724-benchmark:
    <<: *x-model-benchmark-rocm-724
    environment:
      <<: *qwen36-27B-MTP-env

  qwen36-27B-MTP-rocm-7-14-benchmark:
    <<: *x-model-benchmark-rocm-7-14
    environment:
      <<: *qwen36-27B-MTP-env


  # --------------------------------------------------------------------------------------------------------------------------------------------------------------
  qwen3-4b-128k-q6:
    <<: *x-model-rocm-7-14
    environment: &qwen3-4b-128k-q6-env
      <<: *x-model-rocm-7-14-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--Qwen3-4B-128K-GGUF/snapshots/a21842b9582c3888b30568b8e84afe533275f646/Qwen3-4B-128K-UD-Q6_K_XL.gguf
    ports:
      - 8150:8080

  qwen3-4b-128k-q6-voice:
    <<: *x-model-rocm-7-14
    environment: &qwen3-4b-128k-q6-env
      <<: *x-model-rocm-7-14-env
      LLAMA_ARG_MODEL: /huggingface/hub/models--unsloth--Qwen3-4B-128K-GGUF/snapshots/a21842b9582c3888b30568b8e84afe533275f646/Qwen3-4B-128K-UD-Q6_K_XL.gguf
      # Direct response mode, non-thinking-mode, give immediate response, better UX for voice chat
      LLAMA_ARG_REASONING: off
    ports:
      - 8155:8080

  qwen3-4b-128k-q6-rocm-723-benchmark:
    <<: *x-model-benchmark-rocm-723
    environment:
      <<: *qwen3-4b-128k-q6-env

  qwen3-4b-128k-q6-rocm-724-benchmark:
    <<: *x-model-benchmark-rocm-724
    environment:
      <<: *qwen3-4b-128k-q6-env

  qwen3-4b-128k-q6-rocm-7-14-benchmark:
    <<: *x-model-benchmark-rocm-7-14
    environment:
      <<: *qwen3-4b-128k-q6-env



  # ---------------------------------------------------------------------------------------------------------------------------------

  # Kokoro TTS
  kokoro-tts:
    profiles:
      - model
      - tts
    image: ghcr.io/remsky/kokoro-fastapi-gpu:latest
    environment:
      API_LOG_LEVEL: INFO
    ports:
      - 8880:8880

  # I think I built this variant
  # I have this in my shell history:
  #   docker compose run --rm docker-client save ghcr.io/remsky/kokoro-fastapi-rocm:latest-amd64 | podman load
  kokoro-tts-rocm:
    <<: *x-engine
    profiles:
      - model
      - tts
    #image: ghcr.io/remsky/kokoro-fastapi-rocm:latest-amd64
    image: berne/kokoro-fastapi-rocm:latest-amd64
    environment:
      API_LOG_LEVEL: INFO
    ports:
      - 8890:8880

